[package]
org = "chathura"
name = "simpleEDI"
version = "0.1.1"
distribution = "2201.4.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org="chathurace"
name="edi"
version="0.5.0"
repository="local"